version: '3.1'

services:
  web:
    build: ./ticketscan-backend/
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - "db"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ticketscan
      POSTGRES_PASSWORD: ticketscan
      POSTGRES_DB: ticketscan

  adminer:
    image: adminer
    restart: always
    ports:
      - 8001:8080
