version: '3.1'

volumes: 
  postgresql-data:

services:
  rest:
    build: ./ticketscan-backend/
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - "db"

  web:
    image: nginx:stable-alpine
    depends_on:
      - "rest"
    ports:
      - "80:80"       # http
    volumes:
      - ./ticketscan-frontend:/var/www/:ro

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ticketscan
      POSTGRES_PASSWORD: ticketscan
      POSTGRES_DB: ticketscan
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8001:8080
